name: merge to main from develop

on:
  schedule:
    - cron: "00/10 * * * *"
jobs:
  stagePromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: develop
